### PR TITLE
Fee amount update in pay online screen

### PR DESCRIPTION
**Pull request by mounikahmcts**
Fee details should be dynamic in /pay/online section where payment will be processed

### CODE REVIEW

**Comment by dtaylor7** [comment]
@hosainnet have you seen other PR?

**Comment by hosainnet** [comment]
Yes I have.. It's just that we're coding extra functionality here which is based on something that is not in master and still being tested, so it's subject to change

**Comment by dtaylor7** [comment]
> Yes I have.. It's just that we're coding extra functionality here which is based on something that is not in master and still being tested, so it's subject to change

And how do you propose i update a file that has moved in a previous PR?

**Comment by hosainnet** [comment]
It should be done in the same branch where the dependent code is (if it's relevant) or the dependent code should be in master already, just my opinion

**Comment by mounikahmcts** [comment]
> It should be done in the same branch where the dependent code is (if it's relevant) or the dependent code should be in master already, just my opinion



> It should be done in the same branch where the dependent code is (if it's relevant) or the dependent code should be in master already, just my opinion

-- This is a bug and thought the review in the same PR will make people spend too much time on reviewing complete changes, I have created new PR so that only diff can be reviewed, later can be merged to base PR.

**Comment by dtaylor7** [comment]
@hosainnet a crap, thought this convo was for a different PR: https://github.com/hmcts/div-respondent-frontend/pull/212...

**Pull request merged**
