### PR TITLE
[PREVIEW] CCD e2e tests for verification that all case details arrive as expected in CCD

### PR DESCRIPTION
**Pull request by Rob-Doherty**
# Description

This change provides 2 full e2e journeys, from Divorce into CCD, verifying the case data that the court staff would see. This gap in testing was highlighted during a recent production bug, and a task was added to JIRA (DIV-3016).

The aim of this change is to act as a business integration test that can verify all the various services are working together correctly, and avoid discrepancies between the Divorce CCD configuration and the Divorce service. It calls the CCD Print endpoint, and compares that against a static `paymentDivorceCcdCaseData.js`.

Fixes # DIV-3016

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] This is a test-only change

# How Has This Been Tested?

This has been tested locally against CCD.

**Test Configuration**:

* Hardware:
* O/S and version:
* JDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Rob-Doherty** [comment]
Not be merged until it has been configured as a separate "BAT" test to only run overnight - otherwise this will tether Divorce frontend build with CCD availability. not acceptable. needs more work
🚫

**Comment by hosainnet** [comment]
Hi, what's the state of this?

**Comment by hosainnet** [comment]
Yes, exactly :D

**Comment by tchow8** [comment]
Old now, may be moved to another repo. Closing for now, do not delete the branch please.

**Pull request closed without merging**
