### PR TITLE
[PREVIEW] Use fee returned from Fee and payments service on UI

### PR DESCRIPTION
**Pull request by borislavpetrovhmcts**
# Description

Removes Fee register service, gets the fee from Fees and Payments service

Fixes # DIV-2797

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested locally, unit tests, e2e tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tchow8** [comment]
Seems good, can you remove fee-register from the CNP infrastructure files as well please maybe?

**Comment by borislavpetrovhmcts** [comment]
There might be conflicts, it depends which PR will be merged first

**Comment by dtaylor7** [comment]
I mean, are you using the latest urls? as per the the other PR?

**Comment by MOsinloye** [comment]
This has been tested and passed. 

All payments pages returned the right figure of £550 for payment. 

Most of the screenshot attached are out of synch.

Ready for sign off

**Comment by MOsinloye** [comment]
Signed off by @Oonagh  and ready for merge now

**Comment by Rob-Doherty** [comment]
There's been an issue on AAT, so I'm un-deleting the branch

**Pull request merged**
